export const siteConfig = {
  name: 'HostHive',
  description: 'In-depth web hosting reviews, comparisons, and guides. Find the best hosting for WordPress, ecommerce, agencies, and more.',
  url: 'https://hosthive.net',
  logo: 'HostHive',
  author: 'HostHive Team',
  email: 'info@hosthive.net',
  social: {
    twitter: 'https://twitter.com/hosthive',
    facebook: 'https://facebook.com/hosthive',
    linkedin: 'https://linkedin.com/company/hosthive',
  },
  nav: [
    { label: 'Home', href: '/' },
    { label: 'Reviews', href: '/reviews' },
    { label: 'Comparisons', href: '/comparisons' },
    { label: 'Guides', href: '/guides' },
    { label: 'About', href: '/about' },
  ],
  affiliatePrograms: {
    bluehost: { name: 'Bluehost', affiliateUrl: 'https://hosthive.net/go/bluehost', commission: '65+ per sale' },
    siteground: { name: 'SiteGround', affiliateUrl: 'https://hosthive.net/go/siteground', commission: '50+ per sale' },
    hostinger: { name: 'Hostinger', affiliateUrl: 'https://hosthive.net/go/hostinger', commission: '60+ per sale' },
    cloudways: { name: 'Cloudways', affiliateUrl: 'https://hosthive.net/go/cloudways', commission: 'Up to 125 per sale' },
    wpengine: { name: 'WP Engine', affiliateUrl: 'https://hosthive.net/go/wpengine', commission: '200+ per sale' },
    kinsta: { name: 'Kinsta', affiliateUrl: 'https://hosthive.net/go/kinsta', commission: 'Up to 500 per sale' },
  },
  keywords: 'web hosting reviews, best hosting, WordPress hosting, hosting comparison, cheap hosting, VPS hosting, cloud hosting',
  og: { image: 'https://hosthive.net/og-image.png', type: 'website' },
};
